### ISSUE TITLE
To-do list for full coupling

### ISSUE THREAD

**Issue by vitesh13** [vitesh13/Simulation_runner#8]
- [x] Send signals and get expected behaviour
- [x] Trigger to send signals
- [x] Copy the file at inc0
- [x] Handling different output frequencies (copy paste idea)
- [x] Regrid data
- [x] Need to think about regrid frequency based on the strain (look at the displacement value being over a threshold)
- [x] Need to think about CA freqeuncy (maximum velocity and then calculate time after which we would need CA)
- [x] Grain rotation accumulation with reset of zero for DRX nuclei
- [x] Frequency to check the dislocation density (doing it every increment is extreme and slow)
- [x] inheritance of growth length from CA: check relevance (see comment below)
- [x] Need to keep record of increment right after DRX trigger restart for post-processing/visualization
- [x] Need to keep record of increment at which DRX trigger happens for post-processing/visualization
- [x] Create input for CA
- [x] Convert CA output to DAMASK restart input

**Comment by vitesh13** [comment]
For now I do the velocity trigger even after restart and that seems to solve the problem of regrid frequency and CA frequency for now

**Comment by vitesh13** [comment]
Inheritance of growth length of CA:
Is it a really big issue?
Test:
1. Deformation + trigger
2. Run CA for 10s
3. Run CA in steps of 0.1,1,2,5 seconds till 10 seconds. 

Check the test for different strain rates

**Comment by vitesh13** [comment]
Handling orientation changes:
1. Treat similar to rho as the interfaces grow. In case of MDRX interfaces, the change in orientation will get set to 0. 
2. For the case of interfaces (GG interfaces), the orientation change will get inherited.
3. Write out the orientation change to a file
4. Start the next deformation step and calculate the orientation change for that particular step. 
5. Then regrid the orientation change before the deformation step and add it to the orientation changes due to the current deformation step. 

The advantage of the method is the removal of the need to look for history of each point everytime during calculöation of the orientation changes

**Comment by vitesh13** [comment]
Overall the MPI based functions do not work perfect when the increments are getting converged too fast. 
This was seen in the function `run_restart_DRX`, where the signal for pause was sent, but by the time all the processes pause already some increments are recorded in the `HDF5 `file. 
This did not happen however for the case of non-restart simulation, where the function `run_and_monitor_simulation` was used. 
This is strange even though both the functions have nearly the same algorithm and signal handling.

**Comment by vitesh13** [comment]
Overall the whole strategy works!
Needs some further additions and therefore the checklist has been expanded
